### ISSUE TITLE
Issue when obfuscating

### ISSUE THREAD

**Issue by Z3R0-cmd** [Tigermouthbear/nebulous#1]
I have this problem. I also included my config.json at the botton
When I try and obf my client this happens:

 _   _      _           _                 
| \ | |    | |         | |                
|  \| | ___| |__  _   _| | ___  _   _ ___ 
| . ` |/ _ \ '_ \| | | | |/ _ \| | | / __|
| |\  |  __/ |_) | |_| | | (_) | |_| \__ \
\_| \_/\___|_.__/ \__,_|_|\___/ \__,_|___/
v0.1
Created by Tigermouthbear

StringPooler completed in 32 milliseconds
StringEncryptor completed in 500 milliseconds
NumberPooler completed in 39 milliseconds
FieldRenamer completed in 549 milliseconds
ClassRenamer completed in 217 milliseconds
MemberShuffler completed in 9 milliseconds
FullAccessFlags completed in 3 milliseconds
NOPRemover completed in 31 milliseconds
LineNumberRemover completed in 21 milliseconds
GotoInliner completed in 31 milliseconds
Exception in thread "main" java.lang.IllegalArgumentException: Class versions V1_5 or less must use F_NEW frames.
	at org.objectweb.asm.MethodWriter.visitFrame(MethodWriter.java:779)
	at org.objectweb.asm.tree.FrameNode.accept(FrameNode.java:143)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:749)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:462)
	at dev.tigr.nebulous.util.Utils$DefaultImpls.writeBytes(Utils.kt:54)
	at dev.tigr.nebulous.util.Utils$Companion.writeBytes(Utils.kt:15)
	at dev.tigr.nebulous.Nebulous.saveJar(Nebulous.kt:156)
	at dev.tigr.nebulous.Nebulous.saveFile(Nebulous.kt:134)
	at dev.tigr.nebulous.Nebulous.run(Nebulous.kt:87)
	at dev.tigr.nebulous.MainKt.main(Main.kt:25)

{
    "input": "input.jar",
    "output": "output.jar",
    "exclusions": [
        "net/azuraclient/mixins/"
    ],
    "StringPooler": true,
    "StringEncryptor": true,
    "NumberPooler": true,
    "FieldRenamer": true,
    "MethodRenamer": false,
    "ClassRenamer": true,
    "ClassRenamerPrefix": "net/azuraclient/client/",
    "MemberShuffler": true,
    "FullAccessFlags": true,
    "DebugInfoRemover": false,
    "NOPRemover": true,
    "LineNumberRemover": true,
    "GotoInliner": true,
    "GotoReturnInliner": false
}

**Comment by master7720** [comment]
```net/azuraclient/client/``` lol

**Comment by Z3R0-cmd** [comment]
not my fault a intent.store client chose the same name

**Comment by master7720** [comment]
skid

**Comment by Z3R0-cmd** [comment]
truly, this is the pinnacle of the human species.
